package com.test.admin.auth;

public enum AdminRole {
    ROLE_SUPER,
    ROLE_NOTICE_ALL,
    ROLE_NOTICE_READ,
    ROLE_NOTICE_CREATE,
    ROLE_NOTICE_UPDATE,
    ROLE_NOTICE_DELETE,
    ROLE_NUTRI_ALL,
    ROLE_NUTRI_READ,
    ROLE_NUTRI_CREATE,
    ROLE_NUTRI_UPDATE,
    ROLE_NUTRI_DELETE,
    ROLE_REVIEW_ALL,
    ROLE_REVIEW_READ,
    ROLE_REVIEW_DELETE,
    ROLE_ADMIN_ALL,
    ROLE_ADMIN_READ,
    ROLE_ADMIN_CREATE,
    ROLE_ADMIN_UPDATE,
    ROLE_ADMIN_DELETE;
}
